services:

  caddy:
    image: caddy
    container_name: caddy
    environment:
      - RICARDO_BACKEND_DOMAIN=${RICARDO_BACKEND_DOMAIN}
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./volumes/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./volumes/caddy/data/:/data/
      - ./volumes/caddy/config/:/config/
      - ./volumes/caddy/index.html:/www/html/index.html
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3

  grafana:
    build:
      context: ./submodules/grafana
    container_name: grafana
    user: "${UID}:${GID}"
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=TRUE
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=200ms
      - GF_SECURITY_ANGULAR_SUPPORT_ENABLED=TRUE
    ports:
      - 3000:3000
    volumes:
      - ./volumes/grafana/grafana.db:/var/lib/grafana/grafana.db
      - ./volumes/grafana/img:/usr/share/grafana/public/img/bg
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3

  ricardo-backend:
    build:
      context: ./submodules/Ricardo-Backend
    container_name: ricardo-backend
    user: "${UID}:${GID}"
    environment:
      - RICARDO_BACKEND_DEVICE=${SERIAL_PATH}
      - RICARDO_BACKEND_BAUD=1036800
    ports:
      - 1337:1337
      - 1338:1338
    volumes:
      - ./volumes/ricardo-backend/config/:/ricardo-backend/Config/
      - ./volumes/ricardo-backend/fakedata/:/ricardo-backend/ricardobackend/flaskinterface/emitter/data/:ro
      - ./volumes/ricardo-backend/logs/:/ricardo-backend/Logs/
    group_add:
      - dialout
    devices:
      - ${SERIAL_PATH}:${SERIAL_PATH}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3

  ricardo-commandserver:
    build:
      context: ./submodules/Ricardo-CommandServer
    container_name: ricardo-commandserver
    user: "${UID}:${GID}"
    environment:
      - RICARDO_COMMANDSERVER_BACKEND_HOST=ricardo-backend
    ports:
      - 1339:1339
    volumes:
      - ./volumes/ricardo-commandserver/Commands/:/ricardo-commandserver/Commands
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3

  ricardo-influxrelay:
    build:
      context: ./submodules/Ricardo-InfluxRelay
    container_name: ricardo-influxrelay
    user: "${UID}:${GID}"
    volumes:
      - ./volumes/ricardo-influxrelay/config/config.yml:/ricardo-influxrelay/config/config.yml:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3
    profiles: ['dev']

  questdb:
    image: questdb/questdb
    container_name: questdb
    environment:
      - QDB_PG_READONLY_USER_ENABLED=true
    volumes:
      - ./volumes/questdb/:/var/lib/questdb/
    ports:
      - 9001:9000
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3
    profiles: ['dev']
