sockets:
  - url: http://ricardo-backend:1337
    tags:
      source: local

handlers:
  - type: influxdb
    namespace: /telemetry
    url: http://questdb:9000
    token: ""
    org: ICLR
    bucket: telemetry
